apiVersion: v1
kind: Service
metadata:
  name: kuma-demo-api
  namespace: kuma-app
spec:
  selector:
    app: kuma-demo-api
  ports:
  - name: api
    port: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-demo-api
  namespace: kuma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma-demo-api
  template:
    metadata:
      labels:
        app: kuma-demo-api
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
      - image: kvn0218/kuma-demo-api:latest
        name: kuma-demo-api
        env:
        - name: ES_HOST
          value: "http://elasticsearch:80"
        - name: REDIS_HOST
          value: "redis-master"
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
      - name: marketplace-fe
        image: kvn0218/kuma-demo-fe:latest
        ports:
        - containerPort: 8080